---
apiVersion: v1
kind: Service
metadata:
  name: opshell
  namespace: development
  labels:
    app: opshell
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: opshell
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opshell
  namespace: development
  labels:
    app: opshell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opshell
  template:
    metadata:
      labels:
        app: opshell
    spec:
      containers:
        - name: opshell
          image: opshell/opshell:latest
          ports:
            - containerPort: 80
              name: http
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: opshell-ingress
  namespace: development
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - dev.opshell.io
    secretName: opshell-tls
  rules:
  - host: dev.opshell.io
    http:
      paths:
      - backend:
          serviceName: opshell
          servicePort: 80
