---
apiVersion: v1
kind: Service
metadata:
  name: opshell
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: opshell
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opshell
  labels:
    app: opshell
spec:
  replicas: 3
  selector:
    matchLabels:
      app: opshell
  template:
    metadata:
      labels:
        app: opshell
    spec:
      containers:
      - name: opshell
        image: opshell/opshell:latest
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: opshell-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - opshell.io
    - www.opshell.io
    secretName: opshell-tls
  rules:
  - host: opshell.io
    http:
      paths:
      - backend:
          serviceName: opshell
          servicePort: 80
  - host: www.opshell.io
    http:
      paths:
      - backend:
          serviceName: opshell
          servicePort: 80
