---

- name: configure ssh
  copy:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0644
    backup: 'yes'
  notify:
    - restart openssh

- name: manage authorized keys
  copy:
    src: home/ssh/authorized_keys
    dest: /home/ps/.ssh/authorized_keys
    mode: 0600
    backup: 'yes'

- name: manage ssh config
  copy:
    src: home/ssh/config
    dest: /home/ps/.ssh/config
    mode: 0600
    backup: 'yes'

- name: update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: upgrade all packages
  apt:
    name: '*'
    state: latest

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: remove unneeded dependencies
  apt:
    autoremove: yes

- name: remove useless packages from cache
  apt:
    autoclean: yes
